### ISSUE TITLE
App Won’t Open; Keeps Crashing (Beta)

### ISSUE THREAD

**Issue by theboi** [sst-inc/SST-Announcer-iOS#11]
#### Device
 - Device: `iPhone X`
 - OS: `iOS 13.4.1`

#### App
 - App Version: `11.2`
 - App Build: `2.2`

#### Description
App **beta** just installed, crashes on opening

#### How to Reproduce
Steps to reproduce this issue:
- Install **beta** from TestFlight
- Open App
- Watch the App crash
- Jia Chen asked me to file report on GitHub so here I am

#### Expected behaviour
The app should launch and open

#### Screenshots
The app does not even open

#### Additional context
Nope.

**Comment by jiachenyee** [comment]
WidgetKit was set as Required in the linked binaries. It should be fixed in the next beta
