### ISSUE TITLE
App could not be opened on download. [BUG] 

### ISSUE THREAD

**Issue by Ethan-Chew** [sst-inc/SST-Announcer-iOS#12]
#### Device
 - Device: 2017 Macbook Pro
 - OS: MacOS 11

#### App
 - App Version: 11.2
 - App Build: 2.2

#### Description
When downloading the app, it does not open, and promps an error.
<img width="297" alt="Screenshot 2020-08-11 at 7 18 16 AM" src="https://user-images.githubusercontent.com/50659708/89840584-2ed3b500-dba3-11ea-8ec4-3a53f62a3708.png">

#### How to Reproduce
Download the app from the link given

Steps to reproduce this issue:
1. Open the Google Drive link
2. Download it
3. Open it

#### Expected behaviour
The app is supposed to open

#### Screenshots
<img width="297" alt="Screenshot 2020-08-11 at 7 18 16 AM" src="https://user-images.githubusercontent.com/50659708/89840628-4dd24700-dba3-11ea-8721-e748047b7cee.png">

#### Additional context
nil

**Comment by jiachenyee** [comment]
This seems to be an issue with the development certificates. Your device isn't registered under the account.
